"""Kernel-watch monitor: reads /proc-like fixture trees and emits alerts.

Inputs (fixture layout generated by ``fixtures.proc``):
  identity       endpoint IP (RFC 5737)
  ps             `PID COMM` process lines
  sockets        `local remote uid pid state` lines (hex32:hexport form)
  trace_events   `<epoch> <event> <description>` trace-point simulation events

Detections: known-bad binaries, processes running from temp paths, listening
ports on known-bad ranges, beacon connections to suspicious remote ports, and
trace-event patterns (download, mutation, bind, raw-socket).
"""
from __future__ import annotations

import os
import re
from typing import Any, Dict, List, Optional, Sequence

from .model import Alert

STATE_MAP = {"01": "ESTABLISHED", "0A": "LISTEN", "02": "SYN_SENT", "06": "TIME_WAIT"}


def _net_parse_addr(field: str) -> Optional[tuple]:
    """Parse a /proc/net-style `HEX32:HEXPORT` address to (ip, port).

    The HEX32 is a little-endian 32-bit IPv4 (each dotted-quad octet is stored
    least-significant-first in the hex word), so we reverse the byte order.
    """
    try:
        hexip, hexport = field.split(":")
        if len(hexip) != 8 or len(hexport) not in (4, 8):
            return None
        # little-endian: reverse the 4 bytes to get network (big-endian) order
        raw = bytes.fromhex(hexip)[::-1]
        ip = ".".join(str(b) for b in raw)
        port = int(hexport[-4:], 16)
        return ip, port
    except (ValueError, AttributeError):
        return None


def _mk(ts: float, category: str, severity: int, subject: str, src: str,
        evidence: Dict[str, Any]) -> Alert:
    return Alert(
        ts=ts, module="kernel", category=category, severity=severity, subject=subject,
        src=src, action="log-only", evidence=evidence,
        dedupe_key=f"kernel|{category}|{evidence.get('marker', src)}",
    )


def watch_proc_tree(proc_root: str, config: Optional[Dict[str, Any]] = None) -> List[Alert]:
    cfg = (config or {}).get("kernel", {})
    known_bad = set(cfg.get("known_bad", []))
    bad_ports = set(cfg.get("bad_ports", []))
    beacon_ports = set(cfg.get("beacon_ports", []))
    tmp_paths = tuple(cfg.get("tmp_paths", ["/tmp/", "/dev/shm/", "/var/tmp/"]))
    trace_rules = cfg.get("traces", [])

    host_ip = (_read(_join(proc_root, "identity")) or ["n/a"])[0].strip() or "n/a"
    alerts: List[Alert] = []

    trace_lines = _read(_join(proc_root, "trace_events"))
    epochs = []
    for line in trace_lines:
        parts = line.split(" ", 2)
        if len(parts) == 3:
            try:
                epochs.append(float(parts[0]))
            except ValueError:
                pass
    epoch = max(epochs) if epochs else 0.0

    for pid, comm in _iter_table(_read(_join(proc_root, "ps"))):
        base = comm.rsplit("/", 1)[-1]
        if base in known_bad:
            alerts.append(_mk(epoch, "proc.known_bad", 1,
                              f"suspicious process: {comm} matches known-bad list",
                              host_ip,
                              {"pid": pid, "comm": comm, "marker": base}))
        elif any(comm.startswith(p) for p in tmp_paths):
            alerts.append(_mk(epoch, "proc.tmp_path", 2,
                              f"process running from temp/removable path: {comm}",
                              host_ip, {"pid": pid, "comm": comm, "marker": comm}))

    for row in _read(_join(proc_root, "sockets")):
        fields = row.split()
        if len(fields) < 5:
            continue
        local, remote = fields[0], fields[1]
        pid, state_hex = fields[3], fields[4]
        l_ip, l_port = _net_parse_addr(local) or (None, None)
        r_ip, r_port = _net_parse_addr(remote) or (None, None)
        state = STATE_MAP.get(state_hex, state_hex)
        if l_port in bad_ports:
            alerts.append(_mk(epoch, "socket.suspicious_port", 1,
                              f"process listening on known-abuse port {l_port}",
                              host_ip,
                              {"pid": pid, "local": (l_ip, l_port), "state": state,
                               "marker": f"{pid}-{l_port}"}))
        if r_port in beacon_ports and state == "ESTABLISHED":
            alerts.append(_mk(epoch, "socket.beacon", 2,
                              f"beacon-style connection to {r_ip}:{r_port}",
                              host_ip,
                              {"pid": pid, "remote": (r_ip, r_port), "state": state,
                               "marker": f"{pid}-{r_ip}:{r_port}"}))

    compiled = [(re.compile(r.get("rex", "")), r.get("severity", 2), r.get("type", "trace.unknown"))
                for r in trace_rules]
    for line in _read(_join(proc_root, "trace_events")):
        parts = line.split(" ", 2)
        if len(parts) != 3:
            continue
        ts, event, desc = parts
        for rx, sev, cat in compiled:
            if rx.search(f"{event} {desc}"):
                alerts.append(_mk(float(ts), cat, sev, f"trace-point sim: {desc}",
                                  host_ip, {"event": event, "desc": desc, "marker": event}))

    alerts.sort(key=lambda a: a.ts)
    return alerts


def _join(root: str, name: str) -> str:
    return os.path.join(root, name)


def _read(path: str) -> List[str]:
    if not os.path.exists(path):
        return []
    with open(path, "r", encoding="utf-8") as fh:
        return [ln.rstrip("\n") for ln in fh if ln.strip()]


def _iter_table(lines: Sequence[str]):
    for ln in lines:
        parts = ln.split(None, 1)
        if len(parts) != 2:
            continue
        pid, comm = parts
        try:
            yield int(pid), comm
        except ValueError:
            continue


def watch(proc_root: str, config: Optional[Dict[str, Any]] = None) -> List[Alert]:
    """Public entry point (alias of watch_proc_tree)."""
    return watch_proc_tree(proc_root, config)